### ISSUE TITLE
Switch to using UPM instead of git submodules?

### ISSUE THREAD

**Issue by andybak** [Siccity/Graphmesh#4]
It would make this easier to integrate into existing projects.

**Comment by Siccity** [comment]
Personally I find submodules easier to integrate, as they allow me to maintain the code as well, without any workarounds. 

I am unlikely to do any more work on this project anytime soon, but if you want to add support through a PR, go ahead.

**Comment by andybak** [comment]
Thanks. I've actually got some fairly extensive plans so a fork is probably more appropriate than a PR. (I'm going to graft it on to my other project: https://github.com/IxxyXR/Polyhydra/ which currently just has a linear modifier stack for defining the output. )
